language: csharp

before_install:
  - gem install bundler

install:
  - travis_retry bundle install

script:
  - bundle exec rake

rvm:
 - 2.3.1

notifications:
  email: henrik@haf.se

gemfile: Gemfile
